#
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  # build the container image
- name: 'docker.io/library/python:3.7'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'tar -xvf ./lib/datacatalog-python.tar.gz -C ./lib && pip install ./lib/tmp/artman/3923f78f-df98-4123-a92b-28f0755c6320/googleapis/artman-genfiles/python/datacatalog-v1beta1 && pip install ./lib/datacatalog_connectors_commons-1.4.0-py2.py3-none-any.whl && pip install . && python setup.py test'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${TAG_NAME}', '-f', 'Dockerfile.app', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '${_SERVICE_NAME}', '--image', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${TAG_NAME}', '--platform', 'managed', '--region', 'us-central1', '--memory', '1Gi', '--update-env-vars', '${_ENV_PROJECT_ID},${_ENV_LOCATION_ID},${_ENV_METASTORE_DB_HOST}', '--timeout=900']
images:
- gcr.io/$PROJECT_ID/${_SERVICE_NAME}
